branches:
- main
- master
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/github"
- - "@semantic-release/changelog"
  - changelogFile: CHANGELOG.md
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md
    message: |-
      chore(release): ${nextRelease.version} PLAT-0000 [skip ci]
      ${nextRelease.notes}
- - "@semantic-release/exec"
  - verifyReleaseCmd: echo ${nextRelease.version} > nextVersion



